### ISSUE TITLE
Cordova app can't find main.css

### ISSUE THREAD

**Issue by sam3k** [nick-pww/cordova-3-angular#3]
I finally got this working but when I compiled the cordova app, it does not find the main.css. I guess because we don't even store it in the styles folder to begin with but in a .tmp directory the cordova app knows nothing about.

Any ideas?

**Comment by nick-pww** [comment]
Yeah, if you compile things with SASS, you need to set the default output directory for that be in the main app folder, not in .tmp. You are correct that cordova does not know anything about those files.

Would be simple enough changing the following:
compass: {
      options: {
        sassDir: '<%= yeoman.app %>/styles',
        cssDir: '.tmp/styles'
    }
}

to:

compass: {
      options: {
        sassDir: '<%= yeoman.app %>/styles',
        cssDir: '<%= yeoman.app %>/styles'
    }
}

Then adding the .css files to gitignore.

**Comment by sam3k** [comment]
@nick-pww thanks! will test this.

**Comment by sam3k** [comment]
@nick-pww That fixed the issue. Thanks!
